Added sort by year option
mattttvaughn/chronicle pull request #53
Opened 2022-03-24 22:26 UTC by lks-nbg

This extension allows sorting the library by year
Resolves #22

2022-03-24 23:03 UTC, mattttvaughn requested changes
Looks good! Left one little comment

Also, for this we'd need a DB migration strategy for the change to Audiobook since that model is used in BookDatabase.

Should be quick n ez- you can just follow the existing patterns in `BookDatabase.kt` to add a new migration, and make sure to increment the version number on line 76

2022-03-24 23:03 UTC, mattttvaughn commented on app/src/main/java/io/github/mattpvaughn/chronicle/data/model/Audiobook.kt
> +            year = dir.parentYear.takeIf { it != 0} ?: dir.year,
What is the parentYear of a book? Depending on what that is, thinking we probably want to take dir.year as primary here and use parentYear as the ballback

2022-03-25 07:50 UTC, lks-nbg commented on app/src/main/java/io/github/mattpvaughn/chronicle/data/model/Audiobook.kt
> +            year = dir.parentYear.takeIf { it != 0} ?: dir.year,
I found it in the list Metadata of MediaContainer, where the PlexDirectories are extracted. But I agree year should be used as primary and parentYear as fallback.

2022-03-25 07:53 UTC, lks-nbg commented
- Added db migration code
- Changed year to primary and parentYear to fallback

2022-03-25 22:28 UTC, mattttvaughn approved these changes
looks good 👍

2022-03-25 22:43 UTC, pmayeur commented
woot! Thank you! (If you provide an apk, I'm happy to QE)

2022-03-26 19:43 UTC, merged